@WebApi_HostAddress = http://localhost:5089

### 1. POBRANIE WSZYSTKICH OSÓB 
GET {{WebApi_HostAddress}}/api/contacts?page=1&size=10
Accept: application/json

###

### 2. POBRANIE OSOBY PO ID 
GET {{WebApi_HostAddress}}/api/contacts/732b7f3a-ccea-43b0-8e47-eec4a0f0041a
Accept: application/json

###

### 3. UTWORZENIE NOWEJ OSOBY
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Witek",
  "lastName": "Puszek",
  "email": "adam@wsei.edu.pl",
  "phone": "48123456789",
  "position": null,
  "birthDate": null,
  "gender": 0,
  "employerId": null,
  "address": {
    "street": "ul.Szybka 15",
    "city": "Kraków",
    "postalCode": "00-001",
    "country": "Polska",
    "type": 0
  }
}

###

### 4. EDYCJA OSOBY
PUT {{WebApi_HostAddress}}/api/contacts/732b7f3a-ccea-43b0-8e47-eec4a0f0041a
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "email": "jan@wsei.edu.pl",
  "phone": "48987654321",
  "position": "Manager",
  "birthDate": null,
  "gender": 0,
  "employerId": null,
  "address": null
}

###

### 5. DODANIE NOTATKI DO OSOBY
POST {{WebApi_HostAddress}}/api/contacts/732b7f3a-ccea-43b0-8e47-eec4a0f0041a/notes
Content-Type: application/json

{
  "content": "Wojtek to super persona2"
}

###

### 6. POBRANIE NOTATEK OSOBY
GET {{WebApi_HostAddress}}/api/contacts/732b7f3a-ccea-43b0-8e47-eec4a0f0041a/notes
Content-Type: application/json

###

### 6.1 POBRANIE POJEDYNCZEJ NOTATKI 
GET {{WebApi_HostAddress}}/api/contacts/732b7f3a-ccea-43b0-8e47-eec4a0f0041a/notes/d37666fc-49cc-4d18-9120-f8878473b51a
Content-Type: application/json

###

### 7. DODANIE NOTATKI DO NIEISTNIEJĄCEJ OSOBY 
POST {{WebApi_HostAddress}}/api/contacts/00000000-0000-0000-0000-000000000000/notes
Content-Type: application/json

{
  "content": "Notatka"
}

###

### 8. USUNIĘCIE NOTATKI 
DELETE {{WebApi_HostAddress}}/api/contacts/732b7f3a-ccea-43b0-8e47-eec4a0f0041a/notes/5ba8b7b0-c33d-448d-a216-2d48c1766f49
Content-Type: application/json

###
