@WebApi_HostAddress = http://localhost:5089

### 1. POBRANIE WSZYSTKICH OSÓB 
GET {{WebApi_HostAddress}}/api/contacts?page=1&size=10
Accept: application/json

###

### 2. POBRANIE OSOBY PO ID 
GET {{WebApi_HostAddress}}/api/contacts/732b7f3a-ccea-43b0-8e47-eec4a0f0041a
Accept: application/json

###

### 3. UTWORZENIE NOWEJ OSOBY
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Nowak",
  "email": "adam@wsei.edu.pl",
  "phone": "48 123 456 789",
  "position": null,
  "birthDate": null,
  "gender": 0,
  "employerId": null,
  "address": null
}

###



