// <auto-generated />
using System;
using Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    [Migration("20260415052345_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AppCore.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTimeUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasDiscriminator<string>("ContactType").HasValue("Contact");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AppCore.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeCreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("AppCore.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.Entities.CrmRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4d171334-e184-4eb8-8c24-9f5a39d3f645",
                            Description = "Administrator role",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "61b90e34-cea8-4c99-b910-84325dfb49f8",
                            Description = "Sales Manager role",
                            Name = "SalesManager"
                        },
                        new
                        {
                            Id = "5e4dedb4-1604-459c-bc79-6f40d4533da2",
                            Description = "Salesperson role",
                            Name = "Salesperson"
                        },
                        new
                        {
                            Id = "e647b98b-21b0-4bc3-b380-8880aca08c20",
                            Description = "Support Agent role",
                            Name = "SupportAgent"
                        },
                        new
                        {
                            Id = "41ba399f-2da6-4ddd-bb5a-7267d3e17e13",
                            Description = "Read Only role",
                            Name = "ReadOnly"
                        });
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.Entities.CrmUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "696817ea-db8c-4587-b764-7e918a11f19b",
                            CreatedAt = new DateTime(2026, 4, 15, 7, 23, 43, 891, DateTimeKind.Local).AddTicks(4230),
                            Department = "IT",
                            Email = "admin@wsei.edu.pl",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            FullName = "Admin User",
                            LastName = "User",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b8aa8d88-ffc6-4e71-8b12-f6166a8a32ae",
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "admin@wsei.edu.pl"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b5f51595-46b9-435f-884a-103281c3eb45",
                            CreatedAt = new DateTime(2026, 4, 15, 7, 23, 43, 891, DateTimeKind.Local).AddTicks(4413),
                            Department = "Sales",
                            Email = "user@wsei.edu.pl",
                            EmailConfirmed = false,
                            FirstName = "Regular",
                            FullName = "Regular User",
                            LastName = "User",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d291af8d-4e3d-4b32-94cd-3125c2c18740",
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "user@wsei.edu.pl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppCore.Models.Company", b =>
                {
                    b.HasBaseType("AppCore.Models.Contact");

                    b.Property<decimal?>("AnnualRevenue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrimaryContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("REGON")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasIndex("PrimaryContactId");

                    b.HasDiscriminator().HasValue("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("516a34d7-ccfb-4f20-85f3-62bd0f3af271"),
                            ContactStatus = 0,
                            DateTimeCreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "biuro@wsei.edu.pl",
                            Phone = "123567123",
                            Industry = "edukacja",
                            Name = "WSEI",
                            Website = "https://wsei.edu.pl"
                        });
                });

            modelBuilder.Entity("AppCore.Models.Organization", b =>
                {
                    b.HasBaseType("AppCore.Models.Contact");

                    b.Property<string>("ARS")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PrimaryContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasIndex("PrimaryContactId");

                    b.ToTable("Contact", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("Organization_Name");

                            t.Property("PrimaryContactId")
                                .HasColumnName("Organization_PrimaryContactId");

                            t.Property("Website")
                                .HasColumnName("Organization_Website");
                        });

                    b.HasDiscriminator().HasValue("Organization");
                });

            modelBuilder.Entity("AppCore.Models.Person", b =>
                {
                    b.HasBaseType("AppCore.Models.Contact");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.HasIndex("EmployerId");

                    b.HasIndex("OrganizationId");

                    b.HasDiscriminator().HasValue("Person");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d54091d-abc8-49ec-9590-93ad3ed5458f"),
                            ContactStatus = 0,
                            DateTimeCreatedAt = new DateTime(2026, 4, 15, 7, 23, 43, 879, DateTimeKind.Local).AddTicks(1030),
                            DateTimeUpdatedAt = new DateTime(2026, 4, 15, 7, 23, 43, 880, DateTimeKind.Local).AddTicks(2381),
                            Email = "adam@wsei.edu.pl",
                            Phone = "123456789",
                            BirthDate = new DateTime(2001, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Adam",
                            Gender = "Male",
                            LastName = "Nowak",
                            MiddleName = "Jan",
                            Position = "Programista"
                        },
                        new
                        {
                            Id = new Guid("b4dcb17c-f875-43f8-9d66-36597895a466"),
                            ContactStatus = 4,
                            DateTimeCreatedAt = new DateTime(2026, 4, 15, 7, 23, 43, 880, DateTimeKind.Local).AddTicks(3226),
                            DateTimeUpdatedAt = new DateTime(2026, 4, 15, 7, 23, 43, 880, DateTimeKind.Local).AddTicks(3233),
                            Email = "ewa@wsei.edu.pl",
                            Phone = "123123123",
                            BirthDate = new DateTime(2001, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ewa",
                            Gender = "Female",
                            LastName = "Kowalska",
                            MiddleName = "Maria",
                            Position = "Tester"
                        });
                });

            modelBuilder.Entity("AppCore.Models.Contact", b =>
                {
                    b.OwnsOne("AppCore.Models.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("AddressType")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contact");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");

                            b1.HasData(
                                new
                                {
                                    ContactId = new Guid("3d54091d-abc8-49ec-9590-93ad3ed5458f"),
                                    AddressType = 1,
                                    City = "Kraków",
                                    Country = "Poland",
                                    Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                                    PostalCode = "25-009",
                                    Street = "ul. Św. Filipa 17"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("AppCore.Models.Note", b =>
                {
                    b.HasOne("AppCore.Models.Contact", null)
                        .WithMany("Notes")
                        .HasForeignKey("ContactId");
                });

            modelBuilder.Entity("AppCore.Models.Tag", b =>
                {
                    b.HasOne("AppCore.Models.Contact", null)
                        .WithMany("Tags")
                        .HasForeignKey("ContactId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Models.Company", b =>
                {
                    b.HasOne("AppCore.Models.Person", "PrimaryContact")
                        .WithMany()
                        .HasForeignKey("PrimaryContactId");

                    b.Navigation("PrimaryContact");
                });

            modelBuilder.Entity("AppCore.Models.Organization", b =>
                {
                    b.HasOne("AppCore.Models.Person", "PrimaryContact")
                        .WithMany()
                        .HasForeignKey("PrimaryContactId");

                    b.Navigation("PrimaryContact");
                });

            modelBuilder.Entity("AppCore.Models.Person", b =>
                {
                    b.HasOne("AppCore.Models.Company", "Employer")
                        .WithMany("Employees")
                        .HasForeignKey("EmployerId");

                    b.HasOne("AppCore.Models.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Employer");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AppCore.Models.Contact", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("AppCore.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AppCore.Models.Organization", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
